# Generated by Django 5.1.1 on 2024-10-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category',
            new_name='parents',
        ),
    ]
