# Generated by Django 5.1.1 on 2024-10-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_parents_category_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
