# Generated by Django 5.1.1 on 2024-10-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
