# Generated by Django 5.1.1 on 2024-10-10 11:26

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='products/', verbose_name='image'),
        ),
    ]
