# Generated by Django 5.1.2 on 2024-10-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_product_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parents',
            new_name='parent',
        ),
    ]
