# Generated by Django 5.1.1 on 2024-10-15 14:12

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/', verbose_name='image'),
        ),
    ]
